"""
Text Report Generator
Generates plain text reports for easy sharing and accessibility
"""

from datetime import datetime
from typing import Optional


def generate_text_report(diagnosis, patient, include_details: bool = True) -> str:
    """
    Generate a plain text diagnostic report

    Args:
        diagnosis: Diagnosis model instance
        patient: Patient model instance
        include_details: Whether to include detailed findings

    Returns:
        Plain text report string
    """

    lines = []

    # Header
    lines.append("=" * 70)
    lines.append(" " * 20 + "PATHRAD AI DIAGNOSTIC REPORT")
    lines.append("=" * 70)
    lines.append("")

    # Report metadata
    lines.append(f"Report ID: {diagnosis.id}")
    lines.append(f"Case ID: {patient.case_id}")
    lines.append(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("")

    # Patient Information
    lines.append("-" * 70)
    lines.append("PATIENT INFORMATION")
    lines.append("-" * 70)
    lines.append(f"Patient Name: {patient.first_name} {patient.last_name}")
    lines.append(f"Age: {patient.age} years")
    lines.append(f"Sex: {patient.sex}")
    lines.append(f"Location: {patient.location or 'N/A'}")
    lines.append(f"Case ID: {patient.case_id}")

    if patient.chief_complaint:
        lines.append(f"\nChief Complaint:")
        lines.append(f"  {patient.chief_complaint}")

    if patient.clinical_history:
        lines.append(f"\nClinical History:")
        lines.append(f"  {patient.clinical_history}")

    lines.append("")

    # Diagnostic Findings
    if diagnosis.status == "completed":
        lines.append("-" * 70)
        lines.append("DIAGNOSTIC FINDINGS")
        lines.append("-" * 70)

        if diagnosis.primary_diagnosis:
            lines.append(f"\nPrimary Diagnosis:")
            lines.append(f"  {diagnosis.primary_diagnosis}")

        if diagnosis.confidence is not None:
            lines.append(f"\nConfidence Level: {diagnosis.confidence * 100:.1f}%")

        if diagnosis.urgency_level:
            lines.append(f"Urgency: {diagnosis.urgency_level.upper()}")

        # TB Assessment
        if diagnosis.tb_probability is not None:
            lines.append(f"\nTuberculosis Assessment:")
            lines.append(f"  TB Probability: {diagnosis.tb_probability * 100:.1f}%")

            if diagnosis.pathology_result:
                lines.append(f"  AFB Smear: {diagnosis.pathology_result}")

            if diagnosis.bacilli_count is not None and diagnosis.bacilli_count > 0:
                lines.append(f"  Bacilli Count: {diagnosis.bacilli_count}")

        # Findings
        if diagnosis.findings:
            lines.append(f"\nKey Findings:")
            for i, finding in enumerate(diagnosis.findings, 1):
                lines.append(f"  {i}. {finding}")

        # Treatment Plan
        if diagnosis.treatment_plan:
            lines.append(f"\n{'-' * 70}")
            lines.append("TREATMENT PLAN")
            lines.append(f"{'-' * 70}")
            lines.append(diagnosis.treatment_plan)

        # Follow-up
        if diagnosis.follow_up:
            lines.append(f"\n{'-' * 70}")
            lines.append("FOLLOW-UP RECOMMENDATIONS")
            lines.append(f"{'-' * 70}")
            lines.append(diagnosis.follow_up)

        # Human Review Notice
        if diagnosis.human_review_required:
            lines.append("")
            lines.append("=" * 70)
            lines.append("⚠️  IMPORTANT NOTICE")
            lines.append("=" * 70)
            lines.append("This case has been flagged for human specialist review.")
            lines.append("Please consult with a qualified healthcare professional.")
            lines.append("=" * 70)

    else:
        lines.append("-" * 70)
        lines.append("DIAGNOSTIC FINDINGS")
        lines.append("-" * 70)
        lines.append(f"Status: {diagnosis.status.upper()}")
        lines.append("Diagnosis is still being processed.")

    # Footer
    lines.append("")
    lines.append("=" * 70)
    lines.append("DISCLAIMER")
    lines.append("=" * 70)
    lines.append("This report was generated by PathRad AI, a multi-agent diagnostic")
    lines.append("system powered by artificial intelligence. It is intended for")
    lines.append("clinical decision support only and should be reviewed by a")
    lines.append("qualified healthcare professional before making treatment decisions.")
    lines.append("")
    lines.append(
        f"Generated by PathRad AI v2.0.0 on {datetime.now().strftime('%Y-%m-%d')}"
    )
    lines.append("=" * 70)

    return "\n".join(lines)


def save_text_report(diagnosis, patient, output_dir: str = "./reports") -> str:
    """
    Generate and save text report to file

    Returns:
        Path to saved report file
    """
    import os

    # Generate report content
    report_content = generate_text_report(diagnosis, patient)

    # Create filename
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"PathRad_Report_{patient.case_id}_{timestamp}.txt"
    filepath = os.path.join(output_dir, filename)

    # Save to file
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(report_content)

    return filepath
